/** Generate AUDIT.md — SPEC §7 */

/**
 * @param {object} doc
 * @param {string} [root]
 * @returns {string}
 */
export function writeAuditMarkdown(doc, root) {
  const s = doc.stats || {};
  const lines = [];
  lines.push('# Architecture audit — ' + doc.app);
  lines.push('');
  lines.push('Generated by analyzer v' + doc.analyzerVersion + ' at ' + doc.generatedAt + '.');
  lines.push('Source commit: `' + doc.sourceCommit + '`.');
  if (root) lines.push('Root: `' + root + '`.');
  lines.push('');
  lines.push('## Structure');
  lines.push('');
  lines.push('- Files: ' + (s.files || 0));
  lines.push('- Screens: ' + (s.screens || 0));
  lines.push('- Routes: ' + (s.routes || 0));
  lines.push('- Components: ' + (s.components || 0));
  lines.push('- Functions: ' + (s.functions || 0));
  lines.push('- Services: ' + (s.services || 0));
  lines.push('- Stacks: ' + (doc.stacks || []).join(', '));
  lines.push('');
  lines.push('## Dependencies');
  lines.push('');
  lines.push('- Dependency nodes: ' + (s.dependencies || 0));
  lines.push('');
  lines.push('## Data flow');
  lines.push('');
  lines.push('- Display traces: ' + (((doc.traces || {}).display || []).length));
  lines.push('- Hardcoded findings: ' + (s.hardcoded || 0));
  lines.push('');
  lines.push('## Storage & database');
  lines.push('');
  lines.push('- Storage keys/stores: ' + (s.storageKeys || 0));
  lines.push('- Tables: ' + (s.tables || 0));
  lines.push('- Engine: ' + ((doc.database && doc.database.engine) || 'none detected'));
  lines.push('');
  lines.push('## APIs & external services');
  lines.push('');
  lines.push('- External hosts: ' + (s.externalHosts || 0));
  lines.push('- API endpoints: ' + (s.apiEndpoints || 0));
  for (const n of doc.network || []) {
    lines.push('- Host `' + n.host + '` consumers=' + (n.consumers || []).length + ' inCSP=' + !!n.inCSP);
  }
  lines.push('');
  lines.push('## Env / config');
  lines.push('');
  for (const e of doc.env || []) {
    lines.push('- `' + e.name + '` definedIn=' + JSON.stringify(e.definedIn || []) + ' clientExposed=' + !!e.clientExposed + ' looksSecret=' + !!e.looksSecret);
  }
  if (!(doc.env || []).length) lines.push('- (none)');
  lines.push('');
  lines.push('## Orphans / unused / broken');
  lines.push('');
  lines.push('- Orphans: ' + (s.orphans || 0));
  lines.push('- Unused: ' + (s.unused || 0));
  lines.push('- Broken paths: ' + (s.brokenPaths || 0));
  lines.push('- Duplicates: ' + (s.duplicates || 0));
  lines.push('- Security items: ' + (s.securityItems || 0));
  lines.push('');
  lines.push('## Findings');
  lines.push('');
  for (const f of doc.findings || []) {
    lines.push('### ' + f.id + ' · ' + f.kind + ' · ' + f.severity);
    lines.push('');
    lines.push(f.explanation || '');
    for (const ev of f.evidence || []) {
      lines.push('- `' + ev.file + ':' + ev.line + '` — ' + (ev.snippet || ''));
    }
    lines.push('');
  }
  if (!(doc.findings || []).length) lines.push('_No findings._');
  lines.push('');
  lines.push('## Feature completeness');
  lines.push('');
  for (const feat of doc.features || []) {
    lines.push('- **' + feat.name + '**: ' + feat.overall);
  }
  if (!(doc.features || []).length) lines.push('_No features configured._');
  lines.push('');
  lines.push('## Backend presence (supabase / firebase / sqlite)');
  lines.push('');
  const bp = (doc.analyzerCoverage && doc.analyzerCoverage.backendPresence) || {};
  const anyBackend = !!(bp.supabase || bp.firebase || bp.sqlite);
  if (!anyBackend) {
    lines.push('- Verified absence — no Supabase, Firebase, or SQLite usage detected.');
  } else {
    lines.push('- supabase: ' + !!bp.supabase);
    lines.push('- firebase: ' + !!bp.firebase);
    lines.push('- sqlite: ' + !!bp.sqlite);
  }
  lines.push('');
  lines.push('## Analyzer coverage');
  lines.push('');
  const adaptersRun = (doc.analyzerCoverage && doc.analyzerCoverage.adaptersRun) || [];
  if (adaptersRun.length) {
    lines.push('- Adapters run: ' + adaptersRun.join(', '));
  }
  const unresolved = (doc.analyzerCoverage && doc.analyzerCoverage.unresolved) || [];
  if (unresolved.length) {
    for (const u of unresolved) lines.push('- ' + u);
  } else {
    lines.push('- No unresolved notes.');
  }
  lines.push('');
  return lines.join('\n');
}
