// GENERATED by scripts/build-design-tokens.mjs — DO NOT EDIT.
import 'package:flutter/material.dart';

@immutable
class CapTokens extends ThemeExtension<CapTokens> {
  final Color bg;
  final Color bgGrouped;
  final Color surface;
  final Color surface-2;
  final Color separator;
  final Color text;
  final Color textSecondary;
  final Color textTertiary;
  final Color accent;
  final Color accentContrast;
  final Color accentText;
  final Color success;
  final Color successText;
  final Color warning;
  final Color warningText;
  final Color danger;
  final Color dangerText;
  final Color focus;
  final Color scrim;
  final Color materialBar;

  const CapTokens({
    required this.bg,
    required this.bgGrouped,
    required this.surface,
    required this.surface-2,
    required this.separator,
    required this.text,
    required this.textSecondary,
    required this.textTertiary,
    required this.accent,
    required this.accentContrast,
    required this.accentText,
    required this.success,
    required this.successText,
    required this.warning,
    required this.warningText,
    required this.danger,
    required this.dangerText,
    required this.focus,
    required this.scrim,
    required this.materialBar,
  });

  static const light = CapTokens(
    bg: Color(0xFFF2F2F7),
    bgGrouped: Color(0xFFFFFFFF),
    surface: Color(0xFFFFFFFF),
    surface-2: Color(0xFFF2F2F7),
    separator: const Color(0xFF000000), // non-hex: rgba(60,60,67,0.29)
    text: Color(0xFF000000),
    textSecondary: const Color(0xFF000000), // non-hex: rgba(60,60,67,0.6)
    textTertiary: const Color(0xFF000000), // non-hex: rgba(60,60,67,0.3)
    accent: Color(0xFF0A84FF),
    accentContrast: Color(0xFFFFFFFF),
    accentText: Color(0xFF0070E0),
    success: Color(0xFF34C759),
    successText: Color(0xFF248A3D),
    warning: Color(0xFFFF9F0A),
    warningText: Color(0xFFB25000),
    danger: Color(0xFFFF3B30),
    dangerText: Color(0xFFD70015),
    focus: Color(0xFF0A84FF),
    scrim: const Color(0xFF000000), // non-hex: rgba(0,0,0,0.4)
    materialBar: const Color(0xFF000000), // non-hex: color-mix(in srgb, #ffffff 85%, transparent)
  );

  @override
  CapTokens copyWith({Color? accent}) => this;

  @override
  CapTokens lerp(ThemeExtension<CapTokens>? other, double t) => this;
}
