/* GENERATED by scripts/build-design-tokens.mjs — DO NOT EDIT. */
export const capTokens = {
  "meta": {
    "name": "Cap Foundation",
    "version": "0.1.0",
    "updated": "2026-09-14",
    "note": "Canonical Cap Fleet tokens (FND-01). Apps keep only brand overrides."
  },
  "spacing": {
    "space-0": "0",
    "space-1": "2px",
    "space-2": "4px",
    "space-3": "8px",
    "space-4": "12px",
    "space-5": "16px",
    "space-6": "20px",
    "space-7": "24px",
    "space-8": "32px",
    "space-9": "40px",
    "space-10": "48px",
    "space-11": "64px"
  },
  "radius": {
    "radius-xs": "6px",
    "radius-sm": "10px",
    "radius-md": "14px",
    "radius-lg": "20px",
    "radius-full": "999px"
  },
  "type": {
    "largeTitle": {
      "size": "34px",
      "lineHeight": "41px",
      "weight": "700"
    },
    "title1": {
      "size": "28px",
      "lineHeight": "34px",
      "weight": "700"
    },
    "title2": {
      "size": "22px",
      "lineHeight": "28px",
      "weight": "600"
    },
    "title3": {
      "size": "20px",
      "lineHeight": "25px",
      "weight": "600"
    },
    "headline": {
      "size": "17px",
      "lineHeight": "22px",
      "weight": "600"
    },
    "body": {
      "size": "17px",
      "lineHeight": "22px",
      "weight": "400"
    },
    "callout": {
      "size": "16px",
      "lineHeight": "21px",
      "weight": "400"
    },
    "subhead": {
      "size": "15px",
      "lineHeight": "20px",
      "weight": "400"
    },
    "footnote": {
      "size": "13px",
      "lineHeight": "18px",
      "weight": "400"
    },
    "caption1": {
      "size": "12px",
      "lineHeight": "16px",
      "weight": "500"
    },
    "caption2": {
      "size": "11px",
      "lineHeight": "13px",
      "weight": "500"
    }
  },
  "fonts": {
    "font-ui": "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif"
  },
  "colorRoles": [
    "bg",
    "bg-grouped",
    "surface",
    "surface-2",
    "separator",
    "text",
    "text-secondary",
    "text-tertiary",
    "accent",
    "accent-contrast",
    "accent-text",
    "success",
    "success-text",
    "warning",
    "warning-text",
    "danger",
    "danger-text",
    "focus",
    "scrim",
    "material-bar"
  ],
  "themes": {
    "light": {
      "bg": "#f2f2f7",
      "bg-grouped": "#ffffff",
      "surface": "#ffffff",
      "surface-2": "#f2f2f7",
      "separator": "rgba(60,60,67,0.29)",
      "text": "#000000",
      "text-secondary": "rgba(60,60,67,0.6)",
      "text-tertiary": "rgba(60,60,67,0.3)",
      "accent": "#0055cc",
      "accent-contrast": "#ffffff",
      "accent-text": "#0046ad",
      "success": "#34c759",
      "success-text": "#248a3d",
      "warning": "#ff9f0a",
      "warning-text": "#b25000",
      "danger": "#ff3b30",
      "danger-text": "#d70015",
      "focus": "#0a84ff",
      "scrim": "rgba(0,0,0,0.4)",
      "material-bar": "color-mix(in srgb, #ffffff 85%, transparent)"
    },
    "dark": {
      "bg": "#000000",
      "bg-grouped": "#1c1c1e",
      "surface": "#1c1c1e",
      "surface-2": "#2c2c2e",
      "separator": "rgba(84,84,88,0.65)",
      "text": "#ffffff",
      "text-secondary": "rgba(235,235,245,0.6)",
      "text-tertiary": "rgba(235,235,245,0.3)",
      "accent": "#0a84ff",
      "accent-contrast": "#001428",
      "accent-text": "#64d2ff",
      "success": "#30d158",
      "success-text": "#30d158",
      "warning": "#ffd60a",
      "warning-text": "#ffd60a",
      "danger": "#ff453a",
      "danger-text": "#ff453a",
      "focus": "#64d2ff",
      "scrim": "rgba(0,0,0,0.55)",
      "material-bar": "color-mix(in srgb, #1c1c1e 85%, transparent)"
    }
  },
  "elevation": {
    "elev-0": "none",
    "elev-1": "0 1px 2px rgba(0,0,0,.06), 0 1px 1px rgba(0,0,0,.04)",
    "elev-2": "0 8px 24px rgba(0,0,0,.12)"
  },
  "zIndex": {
    "z-base": 0,
    "z-sticky": 10,
    "z-tabbar": 20,
    "z-fab": 30,
    "z-banner": 40,
    "z-sheet": 50,
    "z-modal": 60,
    "z-toast": 70,
    "z-splash": 80
  },
  "motion": {
    "dur-press": "120ms",
    "dur-small": "200ms",
    "dur-sheet": "280ms",
    "dur-page": "350ms",
    "ease-standard": "cubic-bezier(.2,.8,.2,1)",
    "ease-exit": "cubic-bezier(.4,0,1,1)"
  }
} as const;
export type CapTheme = keyof typeof capTokens.themes;
